name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "22 05 1 * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Generate Container Image Tag
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M%SZ')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Auth with GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/binkhq/simpleproxy:${{ steps.date.outputs.date }}
            ghcr.io/binkhq/simpleproxy:latest
